package com.example.weatherforecast.models.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Database entity representing a saved city search result.
 *
 * This class is used by Room persistence library to store and retrieve city data
 * locally. Each instance corresponds to a row in the `citiesNames` table.
 *
 * @property id Unique identifier for the entity; auto-generated by Room.
 * @property city Name of the city (e.g., "Paris").
 * @property country Country code where the city is located (e.g., "FR").
 * @property state Optional state or province name (e.g., "Île-de-France").
 * @property latitude Latitude coordinate of the city's location.
 * @property longitude Longitude coordinate of the city's location.
 *
 * @see Entity for Room database mapping.
 * @see PrimaryKey Indicates that `id` is the primary key with auto-increment enabled.
 */
@Entity(tableName = "citiesNames")
data class CitySearchEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val city: String,
    val country: String,
    val state: String? = null,
    val latitude: Double,
    val longitude: Double
)